title: Vidya Venugopal # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Data Analyst/Data Scientist with 3+ years of experience in data and analytics<br><br>
  MSc, Data Science & Marketing Analytics<br>
  <br><br>
  <a href="https://www.linkedin.com/in/vidyavgopal/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
